services:
  app:
    image: parking-monitor:latest
    privileged: true
    restart: always
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    ports:
      - "3031:3030"
    environment:
      - NODE_ENV=production
      - APP_SERIAL_PORT_FILE=/dev/ttyUSB0
      - APP_ENABLED_LED_MATRIX=true
    volumes:
      - ./log:/app/log
      - ./scripts:/scripts“
